#%RAML 1.0
---

title: Payments Send Charge Reference
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include documentation/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
 badRequest:
  responses:
   400:
    body:
     application/json:
      type: types.errorResponse
      examples:
        badRequest:
         description: Request was incorrect
         value:
            code : BAD_REQUEST
 authorisationHeaderMissing:
  responses:
   401:
     body:
      application/json:
          type: types.errorResponse
          examples:
             badRequest:
               description: The Authorization header is missing
               value:
                code : AUTH_HEADER_MISSING
 authorisationHeaderInvalid:
  responses:
   401:
    body:
     application/json:
       type: types.errorResponse
       examples:
         badRequest:
           description: The value provided for Authorization header is invalid
           value:
            code : AUTH_HEADER_INVALID
 acceptHeaderInvalid:
  responses:
   406:
    body:
      application/json:
        type: types.errorResponse
        examples:
          badRequest:
            description: The accept header is missing or invalid
            value:
                code : ACCEPT_HEADER_INVALID
 internalServerError:
  responses:
   500:
    body:
      application/json:
        type: types.errorResponse
        examples:
          badRequest:
            description: An unexpected condition was encountered
            value:
                code : INTERNAL_SERVER_ERROR
 badGateway:
  responses:
   502:
    body:
      application/json:
        type: types.errorResponse
        examples:
          badRequest:
            description: An invalid response was receievd from an upstream server
            value:
                code : BAD_GATEWAY

/payments/notifications:
  /send-card-payments:
    post:
      displayName: Send card payment
      description: This endpoint accepts the charge reference information and sends it to ETMP via DES.
      is:
        - headers.acceptHeader
        - authorisationHeaderMissing
        - authorisationHeaderInvalid
        - acceptHeaderInvalid
      securedBy: [ sec.x-application ]
      body:
        application/json:
          description: The body contains charge reference information
          example: !include examples/send-card-payments-sample-request.json
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "todo": "complete this when we have sample DES responses"
                }
